### ISSUE TITLE
Missing 'persist=True' in call to track()

### ISSUE THREAD

**Issue by mlopezantequera** [monemati/YOLOv8-Sheep-Detection-Counting#1]
Since the tracker is running in a loop, you must pass `persist=True` to get meaningful ids. (see https://docs.ultralytics.com/modes/track/#persisting-tracks-loop)

https://github.com/monemati/YOLOv8-Sheep-Detection-Counting/blob/71b40f4f37afd0c8a0eb019c7feb0e667707def4/track.py#L37

**Comment by monemati** [comment]
@mlopezantequera Yes you are right, good find, Thank you.
